name: bmi_calculator
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'




dependencies:  
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  provider: ^6.0.5
  syncfusion_flutter_sliders: ^22.2.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter




flutter: 
  
  
  uses-material-design: true
  
  assets:
    - assets/images/male.png
    - assets/images/female.png
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
